from enum import Enum, auto


class Ccy(Enum):
    THB = auto()
    USD = auto()
    AUD = auto()
    HKD = auto()
    CAD = auto()
    NZD = auto()
    SGD = auto()
    EUR = auto()
    HUF = auto()
    CHF = auto()
    GBP = auto()
    UAH = auto()
    JPY = auto()
    CZK = auto()
    DKK = auto()
    ISK = auto()
    NOK = auto()
    SEK = auto()
    RON = auto()
    BGN = auto()
    TRY = auto()
    ILS = auto()
    CLP = auto()
    PHP = auto()
    MXN = auto()
    ZAR = auto()
    BRL = auto()
    MYR = auto()
    IDR = auto()
    INR = auto()
    KRW = auto()
    CNY = auto()
